import { defineConfig } from "oxlint";

export default defineConfig({
    categories: {
        correctness: "error",
        suspicious: "error",
        perf: "error",
    },
    plugins: ["typescript", "unicorn", "oxc", "import"],
    options: {
        typeAware: true,
    },
    jsPlugins: ["oxlint-plugin-complexity", { name: "anti-slop", specifier: "./quality/anti-slop/index.ts" }],
    rules: {
        "eslint/no-unused-vars": "error",
        "eslint/no-var": "error",
        "eslint/no-else-return": "error",
        "eslint/no-param-reassign": "error",
        "eslint/logical-assignment-operators": "error",
        "typescript/no-explicit-any": "error",
        "typescript/no-floating-promises": "error",
        "typescript/no-misused-promises": "error",
        "typescript/no-redundant-type-constituents": "error",
        "typescript/no-unsafe-type-assertion": "error",
        "typescript/no-unnecessary-type-assertion": "error",
        "typescript/await-thenable": "error",
        "typescript/no-misused-spread": "error",
        "import/no-default-export": "error",
        "import/first": "error",
        "unicorn/no-array-for-each": "error",
        "unicorn/prefer-string-starts-ends-with": "error",
        "typescript/prefer-readonly": "error",
        "typescript/consistent-type-definitions": ["error", "type"],
        "complexity/complexity": ["error", { cognitive: 25, cyclomatic: 999 }],
        "oxc/missing-throw": "error",
        "oxc/bad-comparison-sequence": "error",
        "oxc/bad-bitwise-operator": "error",
        "oxc/bad-char-at-comparison": "error",
        "oxc/bad-min-max-func": "error",
        "oxc/bad-object-literal-comparison": "error",
        "oxc/bad-replace-all-arg": "error",
        "oxc/const-comparisons": "error",
        "oxc/double-comparisons": "error",
        "oxc/erasing-op": "error",
        "oxc/misrefactored-assign-op": "error",
        "oxc/number-arg-out-of-range": "error",
        "oxc/uninvoked-array-callback": "error",
        "eslint/no-constant-binary-expression": "error",
        "eslint/no-template-curly-in-string": "error",
        "eslint/no-self-compare": "error",
        "eslint/no-loss-of-precision": "error",
        "eslint/no-promise-executor-return": "error",
        "oxc/only-used-in-recursion": "error",
        "oxc/branches-sharing-code": "error",
        "oxc/no-accumulating-spread": "error",
        "eslint/no-unmodified-loop-condition": "error",
        "eslint/no-await-in-loop": "error",
        "eslint/no-unused-expressions": "error",
        "import/no-duplicates": "error",
        "import/consistent-type-specifier-style": "error",
        "import/no-mutable-exports": "error",
        "unicorn/error-message": "error",
        "unicorn/no-useless-spread": "error",
        "unicorn/no-useless-promise-resolve-reject": "error",
        "import/extensions": "error",
        "import/no-commonjs": "error",
        "import/no-dynamic-require": "error",
        "import/no-cycle": "error",
        "import/no-webpack-loader-syntax": "error",
        "import/unambiguous": "error",
        "eslint/eqeqeq": "error",
        "eslint/array-callback-return": "error",
        "eslint/no-fallthrough": "error",
        "eslint/no-case-declarations": "error",
        "eslint/no-constructor-return": "error",
        "eslint/no-loop-func": "error",
        "eslint/no-unreachable": "error",
        "eslint/getter-return": "error",
        "eslint/no-redeclare": "error",
        "eslint/radix": "error",
        "eslint/no-object-constructor": "error",
        "eslint/no-prototype-builtins": "error",
        "typescript/return-await": "error",
        "typescript/no-import-type-side-effects": "error",
        "typescript/prefer-nullish-coalescing": "error",
        "typescript/no-unnecessary-condition": "error",
        "typescript/switch-exhaustiveness-check": "error",
        "typescript/consistent-type-imports": "error",
        "typescript/no-unsafe-assignment": "error",
        "typescript/no-unsafe-call": "error",
        "typescript/no-unsafe-member-access": "error",
        "typescript/no-unsafe-return": "error",
        "typescript/no-unsafe-argument": "error",
        "typescript/only-throw-error": "error",
        "typescript/restrict-plus-operands": "error",
        "typescript/use-unknown-in-catch-callback-variable": "error",
        "typescript/promise-function-async": "error",
        "typescript/strict-boolean-expressions": "error",
        "typescript/no-non-null-asserted-nullish-coalescing": "error",
        "typescript/no-unnecessary-type-conversion": "error",
        "typescript/no-unnecessary-template-expression": "error",
        "typescript/no-unsafe-enum-comparison": "error",
        "typescript/no-useless-default-assignment": "error",
        "typescript/dot-notation": "error",
        "typescript/prefer-optional-chain": "error",
        "typescript/no-unnecessary-qualifier": "error",
        "unicorn/prefer-array-some": "error",
        "unicorn/prefer-array-find": "error",
        "unicorn/prefer-array-flat-map": "error",
        "unicorn/prefer-set-has": "error",
        "unicorn/prefer-regexp-test": "error",
        "unicorn/prefer-string-replace-all": "error",
        "unicorn/prefer-array-flat": "error",
        "unicorn/prefer-at": "error",
        "unicorn/prefer-type-error": "error",
        "unicorn/no-useless-undefined": "error",
        "unicorn/no-useless-switch-case": "error",
        "unicorn/no-instanceof-array": "error",
        "unicorn/no-array-sort": "error",
        "unicorn/prefer-modern-math-apis": "error",
        "unicorn/prefer-number-properties": "error",
        "typescript/consistent-return": "error",
        "typescript/adjacent-overload-signatures": "error",
        "typescript/unified-signatures": "error",
        "typescript/prefer-find": "error",
        "typescript/prefer-for-of": "error",
        "typescript/no-duplicate-type-constituents": "error",
        "eslint/default-param-last": "error",
        "eslint/prefer-const": "error",
        "eslint/prefer-object-has-own": "error",
        "eslint/prefer-object-spread": "error",
        "eslint/prefer-regex-literals": "error",
        "eslint/prefer-template": "error",
        "eslint/no-useless-concat": "error",
        "eslint/default-case-last": "error",
        "typescript/no-empty-object-type": "error",
        "typescript/non-nullable-type-assertion-style": "error",
        "typescript/prefer-literal-enum-member": "error",
        "typescript/consistent-indexed-object-style": "error",
        "typescript/explicit-module-boundary-types": "error",
        "typescript/explicit-function-return-type": "error",
        "eslint/curly": "error",
        "unicorn/prefer-import-meta-properties": "error",
        "unicorn/no-useless-iterator-to-array": "error",
        "eslint/object-shorthand": "error",
        "anti-slop/no-chained-type-assertions": "error",
        "anti-slop/no-conditional-empty-object-spread": "error",
        "anti-slop/no-known-value-widening": "error",
        "anti-slop/no-module-mocking": "error",
        "anti-slop/no-object-parameters": "error",
        "anti-slop/no-reflect-apply": "error",
        "anti-slop/no-reflect-get": "error",
        "anti-slop/no-shape-in-symbol-names": "error",
        "anti-slop/no-unknown-returns": "error",
        "anti-slop/no-unknown-type-aliases": "error",
        "anti-slop/no-widen-then-assert": "error",
        // These three ask that input be parsed at the I/O boundary, then flag
        // the boundary parsers themselves: requireGithubLogin is the single
        // entry point to the GithubLogin brand, loginFromHosts takes whatever
        // Bun.YAML.parse returned, and usageErrorFrom takes a catch value that
        // useUnknownInCatchVariables types as unknown. There is no earlier
        // place to move the check to. Every other anti-slop rule stays on.
        "anti-slop/no-runtime-typeof": "off",
        "anti-slop/no-unknown-parameters": "off",
        "anti-slop/no-unsafe-dictionary-type": "off",
        "anti-slop/require-safety-comment-for-type-assertion": "error",
    },
    ignorePatterns: ["**/node_modules/**", "quality/anti-slop/**"],
});
